### ISSUE TITLE
Ctrl+Q raise excception

### ISSUE THREAD

**Issue by RomanKharin** [pfalcon/ScratchABit#12]
Pressing Ctrl+Q give me hard-to-copy popup with follwing

```
Traceback (most recent call last):                                  
  File "scratchabit.py", line 237, in handle_edit_key               
    return self.handle_key_unprotected(key)                         
  File "scratchabit.py", line 471, in handle_key_unprotected        
    res = d.loop()                                                  
  File "/home/user/temp/build/ScratchABit/picotui/basewidget.py", li
    self.redraw()                                                   
  File "/home/user/temp/build/ScratchABit/picotui/widgets.py", line 
    w.redraw()                                                      
  File "/home/user/temp/build/ScratchABit/picotui/editor.py", line 5
    self.show_line("", -1)                                          
  File "/home/user/temp/build/ScratchABit/picotui/widgets.py", line 
    l = self.render_line(l)[:self.width]                            
  File "scratchabit.py", line 466, in render_line                   
    return "%08x %s" % l                                            
TypeError: %x format: an integer is required, not str               
```

ps python3.5 example.def

**Comment by pfalcon** [comment]
> hard-to-copy popup

Why it's hard to copy? You can use Shift+mouse to select on screen as usual (usual in mouse-enable console apps). Exception is also logged to scratchabit.log.

Ack, thanks, that's a bug in a dependency lib, picotui. Hope to release fixed version shortly.

**Comment by pfalcon** [comment]
Fixed in master. Requires submodule update.
